name: new_app
description: A new app.

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  